program: SaitoShin10.o getdouble.o
	gcc SaitoShin10.o getdouble.o -o program -lm

SaitoShin10.o: SaitoShin10.c getdouble.h
	gcc -c SaitoShin10.c

getdouble.o: getdouble.c getdouble.h
	gcc -c getdouble.c
